// Open source repositories and developer utilities data model

export const openSourceRepos = [
  {
    name: "halveron-tokens",
    description: "Swiss architectural design tokens and Tailwind CSS preset for modern digital product studios.",
    stars: 342,
    forks: 48,
    language: "TypeScript",
    languageColor: "#3178C6",
    license: "MIT",
    url: "https://github.com/halveron/tokens",
    tags: ["Tailwind CSS", "Design Tokens", "Figma Sync"],
  },
  {
    name: "micro-audio-synth",
    description: "Zero-dependency Web Audio API micro-sound synthesizer for tactile UI clicks, hovers, and feedback tones.",
    stars: 520,
    forks: 64,
    language: "JavaScript",
    languageColor: "#F7DF1E",
    license: "MIT",
    url: "https://github.com/halveron/micro-audio-synth",
    tags: ["Web Audio API", "Micro-Interactions", "Sound Design"],
  },
  {
    name: "next-edge-rate-limiter",
    description: "Lightweight sliding-window rate limiter for Next.js 14 edge API routes with Upstash Redis support.",
    stars: 280,
    forks: 31,
    language: "TypeScript",
    languageColor: "#3178C6",
    license: "Apache-2.0",
    url: "https://github.com/halveron/edge-rate-limiter",
    tags: ["Next.js", "Edge Middleware", "Security"],
  },
  {
    name: "fluid-typography-calc",
    description: "Mathematical clamp() CSS fluid typography generator for responsive editorial web designs.",
    stars: 195,
    forks: 22,
    language: "CSS / JS",
    languageColor: "#563D7C",
    license: "MIT",
    url: "https://github.com/halveron/fluid-typography",
    tags: ["CSS Clamp", "Modular Scale", "Typography"],
  },
];
